#################################################################
#                                                               #
#           Home Assistant Main Configuration File              #
#                                                               #
#################################################################
homeassistant:
# name: !secret name
# temperature_unit: F
# time_zone: !secret timezone
# latitude: !secret latitude
# longitude: !secret longitude
# unit_system: Imperial
# elevation: 0
# customize: !include includes/customize.yaml
#  whitelist_external_dirs:
#    - /config
#  packages: !include_dir_named packages
default_config:
#################################################################
#                                                               #
#                        Customizations                         #
#                                                               #
#################################################################
frontend:
  themes: !include includes/theme-oled.yaml
#  themes: !include_dir_merge_named includes/themes
  extra_module_url:
    - /hacsfiles/custom-sidebar/custom-sidebar.js
    - /hacsfiles/lovelace-card-mod/card-mod.js
#input_text:
#  default_theme:
#    name: amoled
lovelace:
  mode: yaml
  resources: !include /config/resources.yaml
#################################################################
#                                                               #
#                      MQTT Cover                               #
#                                                               #
#################################################################
mqtt:
  - cover:
      id: '15912322314808'
      name: "Boat Lift"
      command_topic: "cmnd/dockrelays_1/POWER"
      state_topic: "stat/dockrelays_1/status"
      availability_topic: "tele/dockrelays_1/LWT"
      qos: 1
#      availability:
#        - topic: "tele/dockrelays_1/LWT"
#      qos: 0
      payload_available: "Online"
      payload_not_available: "Offline"
      payload_open: "ON"
      payload_close: "ON"
      payload_stop: "ON"
      state_open: "open"
      state_closed: "closed"
      device_class: garage
      retain: true
###########################################################################

####################################################
#                                                  #
#                    Includes                      #
#                                                  #
####################################################
automation: !include includes/automations.yaml
#cover: !include includes/cover.yaml
group: !include includes/groups.yaml
input_boolean: !include includes/input_boolean.yaml
input_number: !include includes/input_number.yaml
input_select: !include includes/input_select.yaml
#light: !include includes/lights.yaml
#switch: !include includes/switches.yaml
scene: !include includes/scenes.yaml
script: !include includes/scripts.yaml
binary_sensor: !include includes/binary_sensors.yaml
sensor: !include includes/sensors.yaml
# Define input_select
#################################################################
#                                                               #
#                  Custom Components                            #
#                                                               #
#################################################################
#ecobee:
#  api_key: !secret ecobee_api_key
tts:
  - platform: google_translate
#lutron_caseta_pro:
#  bridges:
#    - host: 10.1.1.59
#      mac: 10:08:2c:9c:50:df
###########################################################
#                                                         #
#                  HomeKit                                #
#    https://www.home-assistant.io/integrations/homekit   #
###########################################################
homekit:
  - filter:
      include_entities:
        - cover.garage_door
        - lock.side_door_lock
        - lock.front_door_lock
        - input_boolean.skimmer
        - input_boolean.swim
        - input_boolean.waterfall
        - input_boolean.waterlevel
        - input_select.pool_mode
    entity_config:
      lock.side_door_lock:
        code: 1000
####################################################
#                                                  #
#                 iOS Actions                      #
#                                                  #
####################################################
ios:
  push:
    categories:
      - name: "Alarm Control" 
        identifier: 'alarm_notification' 
        actions: 
          - identifier: 'SOUND_ALARM'
            title: 'Sound Alarm'
          - identifier: 'SILENCE_ALARM'
            title: 'Dismiss Alarm'
      - name: "FPH_Watchdog" 
        identifier: 'FPH_Watchdog' 
        actions: 
          - identifier: 'OFF'
            title: 'HVAC:OFF?'
          - identifier: 'NONE'
            title: 'FPH:NONE?'
      - name: "Set FPH" 
        identifier: 'set_fph' 
        actions: 
          - identifier: 'FPH+$PH'
            title: 'FPH+$PH'
          - identifier: 'FPH'
            title: 'FPH' 
          - identifier: '$PH'
            title: '$PH' 
          - identifier: 'NONE'
            title: 'NONE' 
      - name: "FPH Control" 
        identifier: 'alarm_notification' 
        actions: 
          - identifier: 'SOUND_ALARM'
            title: 'Sound Alarm'
            destructive: true
            authenticationRequired: false
          - identifier: 'SILENCE_ALARM'
            title: 'Dismiss Alarm'
            destructive: false
            authenticationRequired: true
      - name: "MRA" 
        identifier: 'MRA' 
        actions: 
          - identifier: 'Not_Today?'
            title: 'Not Today?'
      - name: "HVAC WATTS" 
        identifier: 'HVAC_WATTS' 
        actions: 
          - identifier: 'OFF'
            title: 'HVAC:OFF?'
          - identifier: 'NONE'
            title: 'FPH:NONE?'
      - name: 'Robot Vacuum'
        identifier: 'robovac'
        actions:
          - identifier: 'CLEAN_NOW'
            title: 'Begin cleaning now'
            activationMode: 'background'
            authenticationRequired: false
            destructive: false
          - identifier: 'DELAY_CLEAN'
            title: 'Delay cleaning'
            activationMode: 'background'
            authenticationRequired: false
            destructive: false
          - identifier: 'CLEAN_CANCEL'
            title: 'Cancel cleaning'
            activationMode: 'background'
            authenticationRequired: false
            destructive: true
####################################################
#                                                  #
#                      Logger                      #
#                                                  #
####################################################
#logger:
#  default: info
#  logs:
#    custom_components: debug
####################################################
#                                                  #
#                      MQTT                        #
#                                                  #
####################################################
#  mqtt:
#    broker: 10.1.1.202
#    username: !secret mqtt_username
#    password: !secret mqtt_password
# Example configuration.yaml entry with device types
####################################################
#                                                  #
#                   node-red                       #
#                                                  #
####################################################
#################################################################
#                                                               #
#                            Panel                              #
#                                                               #
#################################################################
panel_iframe: 
#  vscode:
#     title: 'VisualCode'
#     url: 'http://10.1.1.10:8443'
#     icon: mdi:visual-studio-code
#  nodered:
#     title: 'Node-RED'
#     url: 'http://10.1.1.203:1880'
#     icon: mdi:sitemap
#################################################################
#                                                               #
#               Proximity Integration                           #
#                                                               #
#################################################################
proximity:
  home:
    devices:
      - person.graham
      - person.christina
    tolerance: 50
    unit_of_measurement: 'mi'
####################################################
#                                                  #
#                     Recorder                     #
#                                                  #
####################################################
recorder:
  purge_keep_days: 180
  db_url: !secret maria_db_info
####################################################
#                                                  #
#                 Shell Command                    #
#                                                  #
####################################################
shell_command:
  pushupdates_to_github: bash /config/pushupdates.sh
####################################################
#                                                  #
#               Xiaomi Miot                        #
#                                                  #
####################################################
#vacuum:
#  - platform: xiaomi_miio
#xiaomi_miot:
#  username: newlon@outlook.com
#  password: Gibj.Q#x9ZYs9m8+
#  server_country: us
####################################################
#                                                  #
#                  Zwave + Zigbee                  #
#                                                  #
####################################################
#zha:
#  database_path: /config/includes/zigbee.db
####################################################
#                                                  #
#                  Templates                       #
#                                                  #
####################################################
#templates: !include includes/templates.yaml

####################################################
#                                                  #
#                  http                            #
#                                                  #
####################################################
http:
  server_host: 0.0.0.0
  use_x_forwarded_for: true
  trusted_proxies:
    - 10.1.1.0/24      # Add the IP address of the proxy server
    - 172.19.0.0/16    # You may also provide the subnet mask
#  server_port: 8123
#  ssl_certificate: /etc/letsencrypt/live/hass.example.com/fullchain.pem
#  ssl_key: /etc/letsencrypt/live/hass.example.com/privkey.pem
#  cors_allowed_origins:
#    - https://google.com
#    - https://www.home-assistant.io
#  use_x_forwarded_for: true
#  ip_ban_enabled: true
#  login_attempts_threshold: 500
    
# http:
#   use_x_forwarded_for: true
#   trusted_proxies:
#     - 172.16.0.0/12
#-------------------
#  ssl_certificate: /ssl/fullchain.pem
#  ssl_key: /ssl/privkey.pem
#  ip_ban_enabled: true
#  login_attempts_threshold: 5