#- alias: "sharkhouse MQTT State on HA Restart"
#  trigger:
#    platform: homeassistant
#    event: start
#  action:
#   - service: mqtt.publish
#     data:
#        topic: cmnd/sharkhouse/backlog
#        payload_template: power1 ;power2 ;power3 ;power4 ;power5; dimmer; state
#- alias: "sharkhouse MQTT Powerretain: On/Off"
#  trigger:
#    platform: homeassistant
#    event: start
#  action:
#    - service: mqtt.publish
#      data:
#        topic: cmnd/sharkhouse/backlog
#        payload_template: SetOption19 1; Delay 100; State
#- alias: "sharkhouse set timezone"
#  trigger:
#    platform: homeassistant
#    event: start
#  action:
#    - service: mqtt.publish
#      data:
#        topic: cmnd/sharkhouse/backlog
#        payload_template: Timezone -5; Delay 100
- alias: "sharkhouse set Timeserver + Daylight Savings Time"
# https://community.home-assistant.io/t/does-anyone-know-how-to-configure-tasmota-dst-st-settings/52861/13
  trigger:
    platform: homeassistant
    event: start
  action:
    - service: mqtt.publish
      data:
        topic: cmnd/sharkhouse/backlog
        payload_template: Backlog Time 0; Timezone 99; TimeDST 0,3,3,1,2,-240; TimeSTD 0,1,11,1,2,-300; NtpServer1 10.1.1.10; NtpServer2 10.1.1.10; NtpServer3 10.1.1.10
- alias: "shell_command.pushupdates_to_github"
# https://www.youtube.com/watch?v=hhv-WqGUy_o
# https://www.home-assistant.io/integrations/shell_command
  trigger:
    platform: homeassistant
    event: start
  action:
    - service: shell_command.pushupdates_to_github
#################################################################################################
#                                                                                               #
#                  notify on zone enter/leave                                                   #
#   https://community.home-assistant.io/t/automation-for-entering-and-leaving-zones/265000/4    #
#################################################################################################
- alias: "notify on shark house proximity zone enter/leave"
  trigger:
    - platform: zone
      entity_id:
         - person.graham
         - person.christina
      zone: zone.shark_house_proximity
      event: enter
    - platform: zone
      entity_id:
         - person.graham
         - person.christina
      zone: zone.shark_house_proximity
      event: leave
  action:
    - variables:
        event: "{{ 'left' if trigger.event == 'leave' else 'arrived at' }}"
        person: "{{ trigger.to_state.attributes.shark_house_proximity }}"
        zone: "{{ trigger.zone.attributes.shark_house_proximity }}"
    - service: notify.mobile_app_grahams_iphone_14
      data:
        message: >
          "{{ person + ' ' + event ' ' + zone }}"
#    - service: notify.mobile_app_christinas_iphone_13
#      data:
#        message: >
#          {{ person + ' ' + event ' ' + zone }}