#Node-Red Input Booleans
swim:
  name: Swim
  initial: off
  icon: mdi:wave
waterfall:
  name: Waterfall
  initial: off
  icon: mdi:wave
skimmer:
  name: Skimmer
  icon: mdi:wave
pooldrain:
  name: Pooldrain
  icon: mdi:wave
spa:
  name: Spa
  initial: off
  icon: mdi:wave
spaclean:
  name: Spaclean
  icon: mdi:wave
nighttime:
  name: Nighttime
  icon: mdi:wave
waterlevel:
  name: waterlevel
  icon: mdi:wave
goodnite:
  name: GoodNite
  icon: mdi:weather-night
#used with appdaemon
door_notify:
  name: Door Notifications
  icon: mdi:alert-circle
#currently in testing
buzz_home:
  name: Buzz Home
  initial: off
  icon: mdi:contact-phone-outline
reset_internet:
  name: Reset Internet
  initial: off
  icon: mdi:wifi-star
security_alarm:
  name: Sound whole house alarm
  icon: mdi:shield-home
homeassistant:
  name: HomeAssistant
  icon: mdi:shield-home
home:
  name: Home
  icon: mdi:shield-home
away:
  name: Away
  icon: mdi:shield-home
g_away:
  name: G.Away
  icon: mdi:shield-home
g_home:
  name: G.Home
  icon: mdi:shield-home
c_away:
  name: C.Away
  icon: mdi:shield-home
c_home:
  name: C.Home
  icon: mdi:shield-home
fire:
  name: Fire
  initial: off
  icon: mdi:shield-home
co:
  name: CO
  initial: off 
  icon: mdi:smoke  
fire_clear:
  name: Fire-Clear
  initial: off  
  icon: mdi:fire
co_clear:
  name: CO-Clear
  initial: off
  icon: mdi:shield-home
guest_home:
  name: Home
  icon: mdi:briefcase-plus
guest_away:
  name: Away 
  icon: mdi:briefcase-minus
no_guest:
  name: None
  icon: mdi:briefcase-off
guest:
  name: Guest
  icon: mdi:briefcase-account
## MANUAL BUTTONS FOR POOL HEAT
#pool_heater:
#  name: Pool $PH
#  icon: mdi:wave
#pool_fph:
#  name: Pool FPH