check_config:
  sequence: []
  alias: Check Configuration
  
clear_lock_jam_status:
  sequence:
  - service: python_script.set_state
    data_template:
      entity_id: binary_sensor.front_door_lock_access_control_lock_jammed
      state: 'off'
  mode: single
  alias: Clear Lock Jam Status
  
mute:
  mode: parallel
  fields:
    media_player:
      description: Media Player that will be mute or unmuted
      example: media_player.living_room
  sequence:
  - service: media_player.volume_mute
    target:
      entity_id: "{{ media_player }}"
    data:
      is_volume_muted: "{{ not state_attr(media_player , 'is_volume_muted') }}"
      
boat_lift_up:
- alias: "Boat Lift Up"
  action:
    - service: mqtt.publish
      data:
        topic: cmnd/boatliftstate/backlog
        payload_template: Backlog Status 1; Power2 on; Status 4
      
boat_lift_down:
- alias: "Boat Lift Down"
# https://community.home-assistant.io/t/does-anyone-know-how-to-configure-tasmota-dst-st-settings/52861/13
  trigger:
    platform: homeassistant
    event: start
  action:
    - service: mqtt.publish
      data:
        topic: cmnd/boatliftstate/backlog
        payload_template: Backlog Status 1; Power2 on; Status 4
